name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > /tmp/private_key
          chmod 600 /tmp/private_key
          scp -i /tmp/private_key -o StrictHostKeyChecking=no -r * $EC2_USER@$EC2_HOST:/var/www/html
          ssh -i /tmp/private_key -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST 'sudo systemctl restart apache2'  # Optional: restart Apache
          rm /tmp/private_key
